---
  - name: Install the ELK stack
    hosts: elk
    become: true
    tasks:

   #Use sysctl module
    - name: Use more memory
      sysctl:
       name: vm.max_map_count
       value: 262144
       state: present
       reload: yes

    # Install docker.io
    - name: Install docker.io
      apt:
        update_cache: yes
        name: docker.io
        state: present

    # Install python3-pip
    - name: Install python3-pip
      apt:
        name: python3-pip
        state: present

    # Install docker module
    - name: Install docker
      pip:
        name: docker
        state: present

    # Use command module
    - name: Install docker
      command: sysctl -w vm.max_map_count=262144

    # Download and install the docker sebp/elk:761
    - name: Install ELK container
      docker_container:
        name: elk
        image: sebp/elk:761
        state: started
        restart_policy: always
        published_ports:
          - 5601:5601
          - 9200:9200
          - 5044:5044

    - name: Persistant Docker service
      systemd:
        name: docker
        enabled: yes